env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  max-len: 'off'
  no-unused-vars: 'off'
  react/prop-types: 'off'
  require-jsdoc: 'off'
  quote-props:
    - error
    - as-needed
    - numbers: true
    # - error
    # - require:
    #     FunctionDeclaration: true
    #     MethodDefinition: true
    #     ClassDeclaration: true
    #     ArrowFunctionExpression: true
    #     FunctionExpression: true
  valid-jsdoc:
    - error
    - requireReturn: false
      requireParamType: false
      requireReturnType: false
