import flare02 from '../images/talents/shiranui-flare--02.png';
import flare02ibukashige from '../images/talents/shiranui-flare--02ibukashige.png';
import flare02smile from '../images/talents/shiranui-flare--02smile.png';
import haachamag from '../images/talents/haato--gangimari.png';
import lamy3dk from '../images/talents/lamy--3dkeibetsu.png';
import lamy3dt from '../images/talents/lamy--3dtehepero.png';
import lamy3dn from '../images/talents/lamy--3dnohohon.png';
import lamy3ds from '../images/talents/lamy--3dsad.png';
import lamy3dp from '../images/talents/lamy--3dpose.png';
import lamy3dpt from '../images/talents/lamy--3dposetere.png';
import mio2s from '../images/talents/okami-mio--02sad.png';
import watames from '../images/talents/tsunomaki-watame--smile.png';
import watamek from '../images/talents/tsunomaki-watame--kossori.png';
import watamet from '../images/talents/tsunomaki-watame--tirari.png';
import watameg from '../images/talents/tsunomaki-watame--gangimari.png';
import watame03d from '../images/talents/tsunomaki-watame--03doya.png';
import watame3ds from '../images/talents/tsunomaki-watame--3dsunglass.png';
import watame3dg from '../images/talents/tsunomaki-watame--3dgangimari.png';

export const talents: [string, string][] = [
  ['flare - 不知火フレア（正月）', flare02],
  ['flare - 不知火フレア（正月・笑顔）', flare02smile],
  ['flare - 不知火フレア（正月・いぶかしげ）', flare02ibukashige],
  ['haachama - 赤井はあと（ガンギマリ）', haachamag],
  ['lamy - 雪花ラミィ（3D・軽蔑）', lamy3dk],
  ['lamy - 雪花ラミィ（3D・てへぺろ）', lamy3dt],
  ['lamy - 雪花ラミィ（3D・のほほん）', lamy3dn],
  ['lamy - 雪花ラミィ（3D・かなしい）', lamy3ds],
  ['lamy - 雪花ラミィ（3D・ポーズ）', lamy3dp],
  ['lamy - 雪花ラミィ（3D・ポーズ照れ）', lamy3dpt],
  ['mio - 大神ミオ（2019新衣装・かなしい）', mio2s],
  ['watame - 角巻わため（笑顔）', watames],
  ['watame - 角巻わため（ガンギマリ）', watameg],
  ['watame - 角巻わため（こっそり）', watamek],
  ['watame - 角巻わため（ちらっ）', watamet],
  ['watame - 角巻わため（2021新衣装ドヤ顔）', watame03d],
  ['watame - 角巻わため（3D・ガンギマリ）', watame3dg],
  ['watame - 角巻わため（3D・サングラス）', watame3ds],
];
